# Generated by Django 3.2.15 on 2022-08-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_platos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='procedencia',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
